version: "3.3"

services:

  mysql:
    image: devops1600/crud-mysql:v0.1
    volumes:
      - /opt/mysql-data:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

  app:
    image: devops1600/crud-node:v0.3
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: crudnodejs
      TITLE: gabo
    depends_on:
      - mysql
    command: ["./start.sh"]
    restart: always

