name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: ls
      run: ls
    
    - name: cd app/test
      run: cd app/test

    - name: start
      run: ls && app/test && npm install && npm test
