name: testing

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: install app dependencies
      run: cd app && npm install 

    - name: Lint
      run: cd app && npm run eslint 

    - name: start test
      run: cd app/test && ls && npm install && npm test


