apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }} #Force to update pod if something is changed in the configMap file
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 3000
          env:
            - name: TITLE  # environment variable name
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}  # ConfigMap name
                  key: TITLE  # ConfigMap key

